# Generated by Django 4.2.3 on 2023-07-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_remove_category_business_business_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
